Update configurations and instructions
unikraft/app-nginx pull request #15
Opened 2023-08-10 15:48 UTC by razvand

Update configurations and instructions and Make-based. Include multiple architectures, compilers, VMMs.

2023-08-11 07:46 UTC, StefanJum requested changes
@razvand in the README file, change all occurrences of `.config.redis-qemu-x86_64` to `.config.redis-qemu-x86_64-9pfs` (under the `###Configure` header). Same for `aarch64`.

2023-08-11 11:38 UTC, razvand commented
> @razvand in the README file, change all occurrences of `.config.redis-qemu-x86_64` to `.config.redis-qemu-x86_64-9pfs` (under the `###Configure` header). Same for `aarch64`.

@StefanJum , solved.

2023-08-12 15:15 UTC, RaduNichita requested changes
Looks good, thanks @razvand 

Please see my comment

2023-08-12 15:15 UTC, RaduNichita commented on README.md
> +./run-qemu-x86_64-initrd.sh
```suggestion
./run-fc-x86_64-initrd.sh
```

2023-08-15 12:23 UTC, StefanJum approved these changes
All good on my side, I'll add the tag after @RaduNichita is happy.

2023-08-15 17:52 UTC, RaduNichita approved these changes
All good with me now, I am happy.

Reviewed-by: Radu Nichita <radunichita99@gmail.com>

2023-08-15 17:54 UTC, StefanJum approved these changes
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-08-15 18:21 UTC, closed without merging