Add KraftKit configuration file for KraftClout
unikraft/app-nginx pull request #16
Opened 2023-08-23 13:08 UTC by razvand

Add `kraft.cloud.yaml` configuration file to build and run for KraftCloud.

Build with:

```console
kraft build --kraftfile kraft.cloud.yaml --target firecracker-x86_64 -j $(nproc)
```

Run with:

```console
sudo kraft net create -n 172.44.0.1/24 kraft0
sudo kraft run --kraftfile kraft.cloud.yaml --network bridge:kraft0 --target firecracker-x86_64 --plat firecracker --arch x86_64 --initrd ./fs0 -a netdev.ipv4_addr=172.88.0.2 -a netdev.ipv4_gw_addr=172.88.0.1 -a netdev.ipv4_subnet_mask=255.255.255.0 -- -c /nginx/conf/nginx.conf
```

2023-08-23 13:36 UTC, marcrittinghaus requested changes
Hey @razvand,

please check out the requested changes and also fix the commit title.

We probably also need to switch to `posix-mmap` due to `lib-ukp-bin`

2023-08-23 13:36 UTC, marcrittinghaus commented on kraft.cloud.yaml
> +  - name: firecracker-x86_64
Rename to `kraftcloud-x86_64`

2023-08-23 13:36 UTC, marcrittinghaus commented on kraft.cloud.yaml
> +      - CONFIG_LWIP_DHCP=y
We don't need (even want!) DHCP

2023-08-23 13:46 UTC, craciunoiuc commented
only one comment from my side: You can use maps instead of lists if you fancy those

`- CONFIG_LWIP_DHCP=y` -> `  CONFIG_LWIP_DHCP: "y"`

2023-08-23 17:26 UTC, StefanJum commented
@razvand running the commands you mentioned, I get this error at runtime:
`could not detect any project targets based on plat="fc" arch="x86_64"`.

Everything build fine, the application image is there. Any idea?

2023-08-23 19:53 UTC, razvand commented
> @razvand running the commands you mentioned, I get this error at runtime: `could not detect any project targets based on plat="fc" arch="x86_64"`.
> 
> Everything build fine, the application image is there. Any idea?

You need the latest [`kraftkit`](https://github.com/unikraft/kraftkit). Download it, do `make devenv`, then `make kraft`, the result executable is part of `dist/kraft`.

2023-08-24 17:06 UTC, StefanJum approved these changes
All good, thanks.

Reviewed-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-08-24 17:08 UTC, craciunoiuc approved these changes
All good here. Thanks!

Reviewed-by: Cezar Craciunoiu <cezar.craciunoiu@unikraft.io>

2023-08-25 05:57 UTC, marcrittinghaus approved these changes
Approved-by: Marc Rittinghaus <marc.rittinghaus@unikraft.io>

2023-08-25 06:14 UTC, closed without merging